apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: ibp25s0, ibp41s0, ibp59s0, ibp92s0, ibp133s0, ibp139s0, ibp146s0, ibp228s0
  name: profiler
  namespace: dev-env
spec:
  containers:
  - command: ["tail", "-f", "/dev/null"]
    name: profiler
    image: gcr.io/mde-cloud/image-repo/ee:20250703034135      
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_PTRACE
        - SYS_ADMIN
        - SYS_RESOURCE    
        - IPC_LOCK    
    resources:
      limits:
        cpu: "60"
        memory: 1600G              
        nvidia.com/gpu: "8"
        nvidia.com/mlnxnics: "8"                
      requests:
        cpu: "60"
        memory: 1600G
        nvidia.com/gpu: "8"
        nvidia.com/mlnxnics: "8"
    volumeMounts:     
    - mountPath: /dev/shm
      name: dshm                            
  volumes:      
  - emptyDir:
      medium: Memory
      sizeLimit: 100Gi
    name: dshm  
  restartPolicy: Never
  imagePullSecrets:
    - name: gcr-cred    